version: '3'
services:
    mongo:
        image: mongominiobackup:latest
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGODB_ADMIN_PASSWORD: example
            AWS_ACCESS_KEY_ID: minio 
            AWS_SECRET_ACCESS_KEY: minio123
            MONGODB_HOST: localhost
            MONGODB_PORT: 27017 
            MONGODB_USER: root 
            MONGODB_PASSWORD: example 
            MONGODB_DATABASE: db
            INIT_RESTORE: 1
            BUCKET: mongobkp
        networks:
                - nt_mongo

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_PORT: 27017
        links:
            - mongo
        networks:
                - nt_mongo

    minio:
        image: minio/minio
        volumes:
            - data:/data
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /data
        networks:
            - nt_mongo

volumes:
    data:      
    
networks:
  nt_mongo:
    driver: bridge